title: Tomislav Hofman
email: contact@hofman.tech
description: >- # this means to ignore newlines until next key
  Personal blog by Tomislav Hofman.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hofman.tech" # the base hostname & protocol for your site
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
